- .github/workflows/reusable-semgrep-workflow.yml
Added reusable workflow for Semgrep validation
> [IDP-948] Added reusable workflow for Semgrep validation

- README.md
Added a quick example usage of the LinearB workflow.
> Update README.md for linearb deployment

- .github/workflows/reusable-jira-workflow.yml
Add support for numbers in jira project id. This is to allow projects like `SGPRO2`
> [IDP-1624] Support numbers in jira project id

- .github/workflows/terraform-create-git-tag.yml
I thought this was supplied by default but it is not 🙀
> IDP-2284 Use github.token to create tags

- .cortex/catalog/service-wl-reusable-workflows.yaml
> [IDP-2311] Update service-wl-reusable-workflows.yaml

- .github/workflows/renovate.yml
> Use current version insteaf of floating version

- .github/workflows/terraform-on-branch-push.yml
- CODEOWNERS
- README.md
- renovate.json
TOPS-800: Replacing gsoft-inc/wl-reusable-workflows by workleap/wl-reusable-workflows
--
Not sure why this PR has been created? Reach TechOps in our public slack channel: #techops-and-friends
Some context on the why of this PR can be found here: https://workleap.slack.com/archives/C02E9KPRQ7P/p1737385211295479
> hotfix/TOPS-800: Renaming gsoft-inc organization to workleap in github.

- renovate.json
Updated properties for Terraform configs.
> Update schema to fix warnings

- .github/workflows/linearb-deployment.yml
- retrieve-managed-secret/action.yml
This action does AZ login and then retrieves the secret that was asked. 
I tried it on this run https://github.com/workleap/renovate-config/actions/runs/14409335496/job/40413379941
> IDP-3311 - Shared action to retrieve a secret

- .github/workflows/terraform-on-branch-push.yml
Add authentication to Terraform Cloud to fetch private modules.
> Add TF Cloud authentication

- .github/workflows/github-template-update-downstream.yml
- README.md
Adding a reusable workflow to sync a GitHub template to all its downstream repositories.
> IDP-3389 Sync downstream GitHub repos with template repo

- .github/workflows/github-template-update-downstream.yml
> Fix string

- .github/workflows/jira.yml
- .github/workflows/reusable-jira-workflow.yml
Jira issue link: https://workleap.atlassian.net/browse/feng-590
> Jira workflow adds a link to the ticket in the PR description

- .github/workflows/terraform-on-branch-push.yml
Jira issue link: [feng-666](https://workleap.atlassian.net/browse/feng-666)
> Use IDP Pool to Prevent TFLINT Throttling

- .github/workflows/reusable-jira-workflow.yml
Jira issue link: [FENG-664](https://workleap.atlassian.net/browse/FENG-664)
Add logic to check if the branch name matches the specified pattern before inserting the JIRA link into the pull request description. Skip insertion if the branch name does not match.
> Ensure JIRA link is added to pull request description based on branch pattern

- .github/workflows/trigger-maintenance-page.yml
Jira issue link: [FENG-664](https://workleap.atlassian.net/browse/FENG-664)
https://dev.azure.com/gsoft/Shared-Assets/_git/Pipeline-Library?path=/jobs/trigger-cloudflare-maintenance-page/trigger-maintenance-page.yaml
> Migrate trigger maintenance page

- .github/workflows/terraform-on-branch-push.yml
Jira issue link: [FENG-707](https://workleap.atlassian.net/browse/FENG-707)
> Use ubuntu-latest

- .github/workflows/terraform-create-git-tag.yml
Jira issue link: [FENG-707](https://workleap.atlassian.net/browse/FENG-707)
> Rollback to ubuntu-latest

- retrieve-managed-secret/action.yml
Jira issue link: [FENG-665](https://workleap.atlassian.net/browse/FENG-665)
> Pipeline stops at the first Write-Error, concat the message to get all info

- README.md
This pull request updates the documentation in the `README.md` file to reflect the inclusion of Cortex alongside LinearB in workflow descriptions.
* Updated the section header to "LinearB and Cortex" to indicate that the workflow now integrates with both LinearB and Cortex. (`README.md`, [README.mdL21-R21](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L21-R21))
> Fix linearb title section to add Cortex

- .github/workflows/required_checks_policy.yml
Jira issue link: [FENG-754](https://workleap.atlassian.net/browse/FENG-754)
> Improve output and remove extra dot

- az-artifact-authenticate/action.yml
Jira issue link: [FENG-574](https://workleap.atlassian.net/browse/FENG-574)
[FENG-574]: https://workleap.atlassian.net/browse/FENG-574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tokens to output

- .github/workflows/jira.yml
- .github/workflows/reusable-jira-workflow-tests.yml
- .github/workflows/reusable-jira-workflow.yml
- extract-jira-issue/action.yml
Jira issue link: [feng-1082](https://workleap.atlassian.net/browse/feng-1082)
This pull request refactors and improves the Jira issue extraction workflow for branch names in GitHub Actions. The main changes include introducing a dedicated composite action for extracting Jira issues, updating the main reusable workflow to use this action, and adding a comprehensive test workflow to validate branch name patterns. These updates enhance maintainability, accuracy, and testability of the Jira integration.
**Jira Issue Extraction Improvements**
* Added a new composite action `extract-jira-issue/action.yml` that reliably extracts Jira issue keys from branch names using a standardized pattern and exposes outputs for downstream steps.
* Updated `.github/workflows/reusable-jira-workflow.yml` to use …
> [Feng-1082] Add test for jira validation

- renovate-terraform.json
Jira issue link: [feng-1144](https://workleap.atlassian.net/browse/feng-1144)
> FENG-1144 Add vertical vertical modules filter to autodiscover
