- README.md
When we added reusable workflows to this repository, we forgot to update the README to clarify the purpose of the repository.
> IDP-1032 Update the README to reflect the new purpose of this repo

- .github/workflows/reusable-jira-workflow.yml
I should now be able to handle automated revert pull requests created from Github which usually have this kind of format
`revert-91-feature/idp-0987`
Currently `revert-91`  would be the first match in the array of matches
> IDP-1088 - Improved regex

- .github/workflows/linearb-deployment.yml
It seems that orgs other than gsoft-inc using this workflow cannot leverage the secrets inherit feature and have to pass in the secret directly to the workflow.
Added the LINEARB_APIKEY as a defined secret as per the documentation [here](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) 
The secret being required doesn't break current usage where secrets are inherited, I tested it.
No, should work the same for current usage
> IDP-1498 - Fix linearB workflows for outside orgs

- .github/workflows/reusable-semgrep-workflow.yml
Give content read permissions to semgrep pipeline. This is necessary when we are using semgrep in a private/internal repository,
> Give content read permissions to semgrep pipeline

- .cortex/catalog/service-wl-reusable-workflows.yaml
This PR adds the cortex descriptor file for this service. This is the file that Cortex will use to populate your service into the catalog.
> IDP-2085 - Add cortex descriptor file

- renovate.json
The diff in https://github.com/gsoft-inc/wl-reusable-workflows/commit/63d6459e3917c8d179f94eb1e46c16c7ce9bacd9 removed autodiscover so our renovate is just not working at all since last week :/
> IDP-2183 Re-enable renovate autodiscover

- .github/workflows/terraform-on-branch-push.yml
Previously, we used a failure code as flow control in the workflow, resulting in the need to re-run the workflow after changes are committed to confirm that the formatting is good. This pattern is discouraged by GitHub, so we'll just mark the check successful right away and save some time and CPU cycles in the process.
Also limits the files committed by this workflow to just the files we expect it to modify for additional safety.
> IDP-2279 Succeed workflow after committing fixes

- .github/workflows/terraform-create-git-tag.yml
These are no longer required, they were left behind in the previous refactor.
> IDP-2284 Remove old inputs

- .github/workflows/terraform-on-branch-push.yml
Use a PAT to trigger new workflow runs on formatting changes, to prevent the Cortex YAML linter from letting failed checks pass.
> Use workleap infra pat to commit formatting

- .github/workflows/terraform-create-git-tag.yml
To pin the action tags to digest shas, I think we should use this renovate setting: https://github.com/renovatebot/renovate/issues/11987 in our renovate config, wdyt @asimmon?
> IDP-2284 Be more specific about action version pin

- .github/workflows/terraform-create-git-tag.yml
It looks like the `v` suffix has vanished upstream??
> IDP-2857 Update github-tag-action version

- .github/workflows/create-stable-release.yml
- README.md
This pull request introduces a reusable workflow to create stable releases from the main branch whenever there are new commits. The key changes include setting up the workflow, fetching the latest stable tag, collecting commit messages, determining the new version based on commit messages, and creating a GitHub release. Updated README.
Developed with the help of ChatGPT and Copilot Edits in VS Code. Tested locally with [nektos/act](https://github.com/nektos/act) at the beginning, then with an actual private repo of mine referencing this new reusable pipeline in this branch.
Supports version bumps according to the commit messages:
- `#major`: bump major
- `#minor`: bump minor
- `#patch`: bump patch (default behavior)
Additional features and behavior:
- Supports new repos without tags (will …
> [IDP-3129] Reusable workflow to create releases from commits pushed since the last stable tag

- .github/workflows/reusable-semgrep-workflow.yml
This permission is required according to the documentation: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-for-sarif-files-generated-outside-of-a-repository
> IDP-3275 Add actions: read perm to semgrep workflow

- .github/workflows/terraform-on-branch-push.yml
We need this to run on self-hosted agents to access firewalled key vaults.
> IDP-3392 Run terraform tools on idp-infra agent pool

- .github/workflows/terraform-on-branch-push.yml
According to [the docs](https://developer.hashicorp.com/terraform/cli/config/config-file), it seems like we don't need to run a terraform login command if `TF_TOKEN_*` is specified. Also, `terraform login` without any arguments is an interactive command that causes the workflow to hang.
> IDP-3392 Don't run terraform login

- .github/workflows/github-template-update-downstream.yml
This pull request updates the workflow for syncing template files to streamline the process of handling changes. Instead of directly pushing to the `main` branch, the workflow now creates and merges a pull request using GitHub CLI commands.
Key change:
* [`.github/workflows/github-template-update-downstream.yml`](diffhunk://#diff-69eb4e7e8ccc7ae43deeb66f9702ff839ccbc08a3009f90f7273a1639b0aa719L103-R104): Replaced the direct `git push origin main` command with `gh pr create --fill` and `gh pr merge --admin --squash --delete-branch` to create a pull request, merge it with admin privileges, squash commits, and delete the branch afterward.
> Set script to create and merge PRs

- .github/workflows/github-template-update-downstream.yml
This pull request updates the workflow for syncing template changes to downstream repositories. The changes streamline the process by introducing a conditional check for ignored repositories, creating a dedicated sync branch, and improving the handling of pull requests and merges.
* Added a conditional check (`if: ${{ !contains(inputs.ignoreRepos, matrix.repo) }}`) to skip processing for repositories listed in the `ignoreRepos` input, simplifying the logic and removing redundant PowerShell code.
* Introduced the creation of a dedicated `sync-template` branch to avoid direct pushes to the `main` branch during template synchronization.
* Updated the pull request creation process to use the `gh pr create` command with the `--fill` flag for default title and body, ensuring consistency and …
> Fix PR creation and merge to main

- .github/workflows/terraform-create-git-tag.yml
Jira issue link: [feng-708](https://workleap.atlassian.net/browse/feng-708)
This pull request updates the GitHub Actions workflow configuration to improve compatibility and maintainability.
* [`.github/workflows/terraform-create-git-tag.yml`](diffhunk://#diff-fd32240d9d325e9b75e6fc990d5e0e5164e6bf1e32e35f399fcc43b86eb48538L9-R9): Updated the `runs-on` property from `[idp]` to `ubuntu-latest` to ensure compatibility with a broader range of environments and improve maintainability.
> Use ubuntu-latest to fix tag creation

- .github/workflows/terraform-on-branch-push.yml
Jira issue link: [FENG-759](https://workleap.atlassian.net/browse/FENG-759)
This pull request updates the GitHub Actions workflow for Terraform to improve security and streamline authentication. The main change involves adding steps to authenticate using a GitHub App token.
* [`.github/workflows/terraform-on-branch-push.yml`](diffhunk://#diff-f99d7c5102c3226875e2e3efd95b30ff80e52179221bf1d81d8d94d14eb726e4R12-R24): Added a step to authenticate with a GitHub App using the `actions/create-github-app-token@v2` action, which generates a token based on the app's ID and private key. The token is then used in the checkout step to enhance security.
> Add auth task back

- .github/workflows/renovate.yml
Jira issue link: [FENG-708](https://workleap.atlassian.net/browse/FENG-708)
This pull request fixes a typo in the environment variable name within the `renovate.yml` workflow file to ensure proper functionality.
* Workflow configuration:
* [`.github/workflows/renovate.yml`](diffhunk://#diff-2f2dcee4f3f279ea8d2f4cd0235f2ab917d8cf1d8e11f4f195a3816afe79af26L59-R59): Corrected the environment variable name from `RENOVATE_TERRAFORM_MODULE_APP_TERRAFORM_IO_TOKEN` to `RENOVATE_TERRAFORM__MODULE_APP_TERRAFORM_IO_TOKEN` to match the expected format.
REF: https://docs.renovatebot.com/self-hosted-configuration/#detecthostrulesfromenv
> Fix ENV variable for Terraform Cloud

- .github/workflows/terraform-auto-doc-check.yaml
- .github/workflows/terraform-linter-check.yaml
- .github/workflows/terraform-standard-checks.yaml
Jira issue link: [FENG-801](https://workleap.atlassian.net/browse/FENG-801)
This pull request introduces three new GitHub Actions workflows to automate various Terraform-related tasks, including documentation updates, linting, and standard checks. These workflows aim to streamline Terraform operations, enforce best practices, and ensure code quality.
* Added `.github/workflows/terraform-auto-doc-check.yaml` to automate the generation and update of Terraform documentation using `terraform-docs`. The workflow commits updates to the `README.md` file.
* Added `.github/workflows/terraform-linter-check.yaml` to perform linting on Terraform code using TFLint. This includes setting up TFLint, loading configurations, and running lint checks with compact output formatting.
* Added …
> Separate the Terraform tasks to improve flexibility

- .github/workflows/terraform-standard-checks.yaml
Jira issue link: [FENG-801](https://workleap.atlassian.net/browse/FENG-801)
This pull request includes a minor update to the `.github/workflows/terraform-standard-checks.yaml` file. The change adjusts permissions by replacing `continue-on-error: true` with `id-token: write` under the `jobs:` configuration.
[FENG-801]: https://workleap.atlassian.net/browse/FENG-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add permission

- .github/workflows/terraform-standard-checks.yaml
Jira issue link: [FENG-810](https://workleap.atlassian.net/browse/FENG-810)
This pull request introduces enhancements to the Terraform validation and testing workflows in `.github/workflows/terraform-standard-checks.yaml`. The changes ensure that only directories containing modified Terraform files are processed, optimizing the workflow by skipping unnecessary validations and tests. Key improvements include dynamically identifying changed directories and iterating over them for validation and testing.
* Added a step to identify directories containing changed `.tf` files and output them as a JSON array (`terraform-dirs`). This ensures that only relevant directories are processed in subsequent steps.
* Modified the validation step to iterate over the detected directories, initializing and …
> Set workflow to run in each modified folders instead of only root

- README.md
Jira issue link: [feng-574](https://workleap.atlassian.net/browse/feng-574)
This pull request updates the `README.md` file to clarify the prerequisites for using the Azure Artifacts Authenticate action. It emphasizes the need for proper permissions for the managed identity associated with the repository.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R68-R70): Added details about the required permissions for the managed identity, specifying that it must have `Stakeholder` access level in the organization and either contributor or reader access to the Azure DevOps feed.
> FENG-574 - Improve readme for nuget auth step

- .github/workflows/terraform-auto-doc-check.yaml
- .github/workflows/terraform-standard-checks.yaml
Jira issue link: [FENG-894](https://workleap.atlassian.net/browse/FENG-894)
This pull request makes a minor update to the GitHub Actions workflows for Terraform checks. The change configures the `changed-files` action to use a newline character as the separator for its output, which can improve compatibility when processing lists of changed files.
* GitHub Actions configuration: Added `separator: "\n"` to the `detect_tf` step in both `.github/workflows/terraform-auto-doc-check.yaml` and `.github/workflows/terraform-standard-checks.yaml` to ensure changed files are separated by newlines. [[1]](diffhunk://#diff-38c06e5858a805eb0a3aca5438681a8d9f16084f50ea923988b1e6caa0d0cfa4R30) [[2]](diffhunk://#diff-f88c446f77e8b2d221809a4e022ec866be423a9539b25eacaa23cf9b52a57bf7R43)
[FENG-894]: …
> Set separator

- .github/workflows/reusable-jira-workflow.yml
Jira issue link: [feng-978](https://workleap.atlassian.net/browse/feng-978)
This pull request introduces a conditional check in the `.github/workflows/reusable-jira-workflow.yml` workflow to skip certain steps if the branch name matches the pattern for copilot fix branches. This helps prevent unnecessary Jira integration steps for automated or fix branches.
Workflow improvements:
* Added a check to skip further steps in the workflow if the branch name matches the `copilot/fix-*` pattern, preventing Jira actions on these branches.
> FENG-978 Bypass jira validation for copilot branches
